### ISSUE TITLE
Simple gulpfile.js error? _ is undefined line:20

### ISSUE THREAD

**Issue by em57** [reflexdemon/slush-angular-gulp#1]
I think gulp won't compile assets with this error nor run gulp serve.

**Comment by reflexdemon** [comment]
Let me take a look at it.

**Comment by reflexdemon** [comment]
Can you please provide me the command-line you tried and that caused the issue?

**Comment by reflexdemon** [comment]
Please try slush-angular-gulp@0.0.5 by doing `npm i -g slush-angular-gulp`

**Comment by reflexdemon** [comment]
you might have to clear your npm cache before running the script. ` npm cache clean`

**Comment by em57** [comment]
Once I have the application scaffold completed, i run  ** gulp serve ** to start the app and build stuff. Since I choose no middleware for proxy support in the setup process, I run into gulp file errors. When i create a project with proxy support, there are no gulp file errors. i believe you are hitting the right place by handling the middle ware variable/settings if they are not required.

**Comment by reflexdemon** [comment]
Gotcha! I have fixed the same now in 0.0.6. Please update with `npm install -g slush-angular-gulp` and let me know if you still running into issues.
