### ISSUE TITLE
Missing bootstrap css injection

### ISSUE THREAD

**Issue by angel1st** [reflexdemon/slush-angular-gulp#26]
Hi there,
I created angular-gulp project as per your description:

    cd my-angular-app
    slush angular-gulp

I start the project by `gulp serve`.

Now, few days after I already put some significant code inside the project, I have just realized, that in my `index.html` file, I missed `bootstrap css` injection, which is supposed to be done by slush generator. Please find enclosed gulpfile.js and give me some directions, since I am not gulp expert and I would prefer keeping my focus over the project, not gulp tuning. 

[gulpfile.js.txt](https://github.com/reflexdemon/slush-angular-gulp/files/38927/gulpfile.js.txt)

bootstrap js injection on the other hand is present, so it seems to me as some kind of inconsistency...

Best Regards,

Angel

**Comment by reflexdemon** [comment]
@angel1st sorry for delayed response. 

We do not require to add the bootstrap css as this will be injected as LESS or any other compiler that you choose to use. The Gulp file that you attached makes me believe that you are using less and the the less styles will be injected to the index.html.
