### ISSUE TITLE
On installation got: "TypeError: this.selection.join is not a function"

### ISSUE THREAD

**Issue by razazaidisd** [reflexdemon/slush-angular-gulp#27]
(*) A Simple example to show how to make server call for non persistance servi
ce calls (heat)

readline.js:924
            throw err;
            ^
TypeError: this.selection.join is not a function
    at Prompt.render (C:\Users\Iqrar.r\AppData\Roaming\npm\node_modules\slush-an
gular-gulp\node_modules\inquirer\lib\prompts\checkbox.js:96:43)
    at Prompt.onEnd (C:\Users\Iqrar.r\AppData\Roaming\npm\node_modules\slush-ang
ular-gulp\node_modules\inquirer\lib\prompts\checkbox.js:122:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\I
qrar.r\AppData\Roaming\npm\node_modules\slush-angular-gulp\node_modules\inquirer
\node_modules\rx-lite\rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (
C:\Users\Iqrar.r\AppData\Roaming\npm\node_modules\slush-angular-gulp\node_module
s\inquirer\node_modules\rx-lite\rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (C:\Users\Iqrar.r\AppData\Roaming\npm\node_m
odules\slush-angular-gulp\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:
63:31)
![image](https://cloud.githubusercontent.com/assets/6624130/14587075/a83e35c2-04bc-11e6-9ee2-1e52659b7aa3.png)

**Comment by reflexdemon** [comment]
@razazaidisd  What version of node are you using?

**Comment by jagzviruz** [comment]
I too got the same error ..

node 6.2.0
slush 1.1.1

**Comment by CJBrew** [comment]
@razazaidisd  what version of node would you suggest using?  I'm seeing the same issue here. 

Node 6.2.2 
Slush 1.1.1
On Windows 8.1

**Comment by reflexdemon** [comment]
@CJBrew  and @jagzviruz @razazaidisd I have found the root cause of the problem. 

1. It was due to the way the checkboxes for inquirer was failing badly.
2. The new inquirer works on promises, unlike the callbacks that was the case earlier.

I have provided a patch and will be working on a long term solution. 

Please use `slush-angular-gulp@0.4.4` and let me know your feedback.
