### ISSUE TITLE
Include Unit Tests

### ISSUE THREAD

**Issue by reflexdemon** [reflexdemon/slush-angular-gulp#5]
Hey, I am in need of help in developing unit tests for this project and any help for this would be great.

**Comment by AquilaSagitta** [comment]
Should switch over to another testing framework, such as Mocha, since Karma doesn't support Node v0.12

**Comment by reflexdemon** [comment]
I am very new to JS side of world and any PR for that is always welcomed. I should be able to fairly adapt to it once I have some help on the initial tests.

**Comment by AquilaSagitta** [comment]
I'm a novice at unit testing. I was mistaken with what I wrote earlier. Karma is a testing environment where as Mocha is a testing framework. I'm not sure if there is an alternative to Karma other then Protractor. Angular Developers might be stuck using Node 0.10

**Comment by AquilaSagitta** [comment]
Looks like there's an issue with karma-phantomjs-launcher and doesn't run on fresh scaffold

**Comment by AquilaSagitta** [comment]
Should look at integrating protractor for end-to-end testing and also using cucumber/gherkin

**Comment by reflexdemon** [comment]
Fixed this by adding appropriate unit test cases.
